name: Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Set CRAN mirror and install renv
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          install.packages("renv")
        shell: Rscript {0}

      - name: Install dependencies
        uses: r-lib/actions/setup-renv@v2
      
      - name: Install devtools
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          utils::install.packages("devtools")
        shell: Rscript {0}

      - name: Run tests
        run: |
          library(devtools)
          devtools::test()
        shell: Rscript {0}